export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical';
export type TransactionType = 'transfer' | 'cash' | 'remittance' | 'pos';
export type PartyType = 'individual' | 'corporate';

export type PbocRule =
  | 'PBOC_LARGE_CASH'
  | 'PBOC_LARGE_TRANSFER'
  | 'HIGH_RISK_COUNTRY'
  | 'SMURFING'
  | 'RAPID_MOVEMENT'
  | 'FREQUENT_CASH';

export interface AmlAlert {
  id: string;
  caseId: string;
  transactionId: string;
  date: string;
  amount: number;
  transactionType: TransactionType;
  senderAccountId: string;
  receiverAccountId: string;
  senderType: PartyType;
  receiverType: PartyType;
  isHighRiskCountry: boolean;
  historicalFrequency: number;
  riskScore: number;
  severity: AlertSeverity;
  triggeredRules: PbocRule[];
  fraudLabel: boolean;
  typology?: string;
  createdAt: string;
}

export const amlAlerts: AmlAlert[] = [
  {
    id: 'ALT-0001',
    caseId: 'CASE-001',
    transactionId: 'TXN-0001',
    date: '2024-11-03',
    amount: 68000,
    transactionType: 'cash',
    senderAccountId: 'ACC-021',
    receiverAccountId: 'ACC-009',
    senderType: 'individual',
    receiverType: 'individual',
    isHighRiskCountry: false,
    historicalFrequency: 18,
    riskScore: 82,
    severity: 'critical',
    triggeredRules: ['PBOC_LARGE_CASH', 'FREQUENT_CASH'],
    fraudLabel: true,
    typology: 'fan-out',
    createdAt: '2024-11-03T09:23:00Z',
  },
  {
    id: 'ALT-0002',
    caseId: 'CASE-001',
    transactionId: 'TXN-0001B',
    date: '2024-11-03',
    amount: 47000,
    transactionType: 'cash',
    senderAccountId: 'ACC-021',
    receiverAccountId: 'ACC-033',
    senderType: 'individual',
    receiverType: 'individual',
    isHighRiskCountry: false,
    historicalFrequency: 18,
    riskScore: 74,
    severity: 'high',
    triggeredRules: ['SMURFING', 'FREQUENT_CASH'],
    fraudLabel: true,
    typology: 'fan-out',
    createdAt: '2024-11-03T11:45:00Z',
  },
  {
    id: 'ALT-0003',
    caseId: 'CASE-002',
    transactionId: 'TXN-0002',
    date: '2024-11-05',
    amount: 3200000,
    transactionType: 'transfer',
    senderAccountId: 'ACC-007',
    receiverAccountId: 'ACC-034',
    senderType: 'corporate',
    receiverType: 'individual',
    isHighRiskCountry: true,
    historicalFrequency: 4,
    riskScore: 78,
    severity: 'high',
    triggeredRules: ['PBOC_LARGE_TRANSFER', 'HIGH_RISK_COUNTRY'],
    fraudLabel: true,
    typology: 'layering',
    createdAt: '2024-11-05T14:01:00Z',
  },
  {
    id: 'ALT-0004',
    caseId: 'CASE-003',
    transactionId: 'TXN-0003',
    date: '2024-11-07',
    amount: 49500,
    transactionType: 'cash',
    senderAccountId: 'ACC-015',
    receiverAccountId: 'ACC-021',
    senderType: 'individual',
    receiverType: 'individual',
    isHighRiskCountry: false,
    historicalFrequency: 9,
    riskScore: 61,
    severity: 'high',
    triggeredRules: ['SMURFING'],
    fraudLabel: true,
    typology: 'smurfing',
    createdAt: '2024-11-07T11:45:00Z',
  },
  {
    id: 'ALT-0005',
    caseId: 'CASE-004',
    transactionId: 'TXN-0004',
    date: '2024-11-09',
    amount: 850000,
    transactionType: 'remittance',
    senderAccountId: 'ACC-003',
    receiverAccountId: 'ACC-071',
    senderType: 'individual',
    receiverType: 'individual',
    isHighRiskCountry: true,
    historicalFrequency: 7,
    riskScore: 68,
    severity: 'high',
    triggeredRules: ['HIGH_RISK_COUNTRY', 'RAPID_MOVEMENT'],
    fraudLabel: false,
    typology: 'rapid-movement',
    createdAt: '2024-11-09T08:55:00Z',
  },
  {
    id: 'ALT-0006',
    caseId: 'CASE-005',
    transactionId: 'TXN-0005',
    date: '2024-11-10',
    amount: 2400000,
    transactionType: 'transfer',
    senderAccountId: 'ACC-042',
    receiverAccountId: 'ACC-088',
    senderType: 'corporate',
    receiverType: 'corporate',
    isHighRiskCountry: false,
    historicalFrequency: 3,
    riskScore: 55,
    severity: 'medium',
    triggeredRules: ['PBOC_LARGE_TRANSFER'],
    fraudLabel: false,
    createdAt: '2024-11-10T10:30:00Z',
  },
  {
    id: 'ALT-0007',
    caseId: 'CASE-003',
    transactionId: 'TXN-0006',
    date: '2024-11-11',
    amount: 28000,
    transactionType: 'cash',
    senderAccountId: 'ACC-056',
    receiverAccountId: 'ACC-021',
    senderType: 'individual',
    receiverType: 'individual',
    isHighRiskCountry: false,
    historicalFrequency: 6,
    riskScore: 38,
    severity: 'medium',
    triggeredRules: ['FREQUENT_CASH'],
    fraudLabel: false,
    typology: 'fan-in',
    createdAt: '2024-11-11T14:20:00Z',
  },
  {
    id: 'ALT-0008',
    caseId: 'CASE-004',
    transactionId: 'TXN-0007',
    date: '2024-11-12',
    amount: 95000,
    transactionType: 'transfer',
    senderAccountId: 'ACC-071',
    receiverAccountId: 'ACC-044',
    senderType: 'individual',
    receiverType: 'individual',
    isHighRiskCountry: false,
    historicalFrequency: 12,
    riskScore: 44,
    severity: 'medium',
    triggeredRules: ['RAPID_MOVEMENT'],
    fraudLabel: false,
    typology: 'rapid-movement',
    createdAt: '2024-11-12T09:00:00Z',
  },
  {
    id: 'ALT-0009',
    caseId: 'CASE-005',
    transactionId: 'TXN-0008',
    date: '2024-11-13',
    amount: 8500,
    transactionType: 'pos',
    senderAccountId: 'ACC-099',
    receiverAccountId: 'ACC-120',
    senderType: 'individual',
    receiverType: 'corporate',
    isHighRiskCountry: false,
    historicalFrequency: 2,
    riskScore: 11,
    severity: 'low',
    triggeredRules: [],
    fraudLabel: false,
    typology: 'cycle',
    createdAt: '2024-11-13T13:15:00Z',
  },
  {
    id: 'ALT-0010',
    caseId: 'CASE-006',
    transactionId: 'TXN-0009',
    date: '2024-11-14',
    amount: 15000,
    transactionType: 'transfer',
    senderAccountId: 'ACC-120',
    receiverAccountId: 'ACC-130',
    senderType: 'individual',
    receiverType: 'corporate',
    isHighRiskCountry: false,
    historicalFrequency: 1,
    riskScore: 8,
    severity: 'low',
    triggeredRules: [],
    fraudLabel: false,
    typology: 'cycle',
    createdAt: '2024-11-14T16:00:00Z',
  },
];
